### ISSUE TITLE
The plugin it work but need to remove dirt screen as loading screen on GeyserMC client

### ISSUE THREAD

**Issue by SunshroomChan** [CreeperNation/BedWars1058-GeyserSupport#1]
That issue comes out because Bedwars1058 plugin after you died, it generating loading screen on Bedrock Client it make annoying for GeyserMC players, and it also show dirt screen on Java Clients as well!

**Comment by BlueTree242** [comment]
Well i think that's issue for original plugin not this addon

**Comment by SunshroomChan** [comment]
> Well i think that's issue for original plugin not this one

Yes i know but when using this it will remove dirt screen away from original likely a feature because on Java it doesn't annoying that much, while on GeyserMC it make annoying when it generated it, im tried find code but still can't fix that on original plugin

**Comment by BlueTree242** [comment]
It's not generated, im not sure but maybe becausd you die which causes world to reload, and geyser just converts that

**Comment by Creeperz653** [comment]
This plugin isn’t even out yet

**Comment by SunshroomChan** [comment]
> This plugin isn’t even out yet

I build the plugin and test it out

**Comment by SunshroomChan** [comment]
> It's not generated, im not sure but maybe becausd you die which causes world to reload, and geyser just converts that

No, even in Java it has dirt screen when you died like i said up there, compare to other Bedwars plugin it doesn't have it

**Comment by Creeperz653** [comment]
> > This plugin isn’t even out yet
> 
> I build the plugin and test it out

The plug-in replaces shop form  which isn’t ready

**Comment by BlueTree242** [comment]
Do you mind me pr a fix to bw1058

**Comment by SunshroomChan** [comment]
> Do you mind me pr a fix to bw1058

well you can check it here https://github.com/andrei1058/BedWars1058/issues/598
